# Generated by Django 4.2.3 on 2023-07-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("film", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=200)),
                ("network", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("rating", models.FloatField()),
            ],
        ),
    ]
